import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { CheckCircle, ChevronLeft } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { VerifyItem } from './VerifyItem';
export function AgentWizardVerifyStep({ createdAgent, usePlugin, pluginGenerated, desktopConfigWritten, pluginToolLabel, pluginVerifyMcp, isManual, onPrevious, onClose, }) {
    const { t } = useTranslation('settings');
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-xs text-gray-400", children: t('agent.wizard.verifyDescription') }), _jsxs("div", { className: "space-y-2", children: [_jsx(VerifyItem, { ok: true, label: t('agent.wizard.verifyAgentCreated', { name: createdAgent.name, id: createdAgent.id }) }), usePlugin && (_jsx(VerifyItem, { ok: pluginGenerated, label: t('agent.wizard.verifyPluginGenerated', {
                            tool: pluginToolLabel,
                        }) })), pluginVerifyMcp && (_jsx(VerifyItem, { ok: desktopConfigWritten, label: t(pluginVerifyMcp.labelKey), hint: t(desktopConfigWritten ? pluginVerifyMcp.hintOkKey : pluginVerifyMcp.hintFailKey) })), isManual && (_jsxs(_Fragment, { children: [_jsx(VerifyItem, { ok: false, label: t('agent.wizard.verifyMcpAdded'), hint: t('agent.wizard.verifyMcpAddedHint') }), _jsx(VerifyItem, { ok: false, label: t('agent.wizard.verifySkillCopied'), hint: t('agent.wizard.verifySkillCopiedHint') }), _jsx(VerifyItem, { ok: false, label: t('agent.wizard.verifyToolRestarted') })] })), _jsx(VerifyItem, { ok: !!createdAgent.last_active, label: t('agent.wizard.verifyFirstConnection'), hint: !createdAgent.last_active ? t('agent.wizard.verifyFirstConnectionHint') : undefined })] }), _jsxs("div", { className: "flex items-center justify-between pt-2", children: [_jsxs("button", { onClick: onPrevious, className: "flex items-center gap-1 text-xs text-gray-400 hover:text-gray-200 transition-colors", children: [_jsx(ChevronLeft, { size: 14 }), t('agent.wizard.prevStep')] }), _jsxs("button", { onClick: onClose, className: "flex items-center gap-1 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 rounded-lg text-xs font-medium text-white transition-colors", children: [_jsx(CheckCircle, { size: 14 }), t('agent.wizard.finish')] })] })] }));
}
