import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { ZoomIn, ZoomOut, Maximize2, Route, Circle } from 'lucide-react';
export function GraphToolbar({ neighborhoodDepth, onNeighborhoodDepthChange, pathMode, pathFrom, onPathModeToggle, showStructureHoles, onStructureHolesToggle, onZoomIn, onZoomOut, onFitAll, connectivityThreshold, onConnectivityThresholdChange, maxConnectivity, graphLimit, onGraphLimitChange, renderedNodeCount, }) {
    const { t } = useTranslation('explorer');
    const DEPTH_OPTIONS = [
        { value: 0, label: t('explorer:toolbar.all') },
        { value: 1, label: t('explorer:toolbar.hop1') },
        { value: 2, label: t('explorer:toolbar.hop2') },
        { value: 3, label: t('explorer:toolbar.hop3') },
    ];
    return (_jsxs("div", { className: "absolute top-3 left-3 right-3 z-10 flex items-center gap-3 flex-wrap", children: [_jsxs("div", { className: "flex items-center gap-1 glass-card rounded-lg px-2 py-1.5 border border-white/10", children: [_jsx("button", { onClick: onZoomIn, className: "p-1 rounded hover:bg-white/10 text-gray-300 hover:text-white transition-colors", title: t('explorer:toolbar.zoomIn'), children: _jsx(ZoomIn, { size: 14 }) }), _jsx("button", { onClick: onZoomOut, className: "p-1 rounded hover:bg-white/10 text-gray-300 hover:text-white transition-colors", title: t('explorer:toolbar.zoomOut'), children: _jsx(ZoomOut, { size: 14 }) }), _jsx("button", { onClick: onFitAll, className: "p-1 rounded hover:bg-white/10 text-gray-300 hover:text-white transition-colors", title: t('explorer:toolbar.fitAll'), children: _jsx(Maximize2, { size: 14 }) })] }), _jsx("div", { className: "flex items-center gap-1 glass-card rounded-lg px-2 py-1.5 border border-white/10", children: DEPTH_OPTIONS.map(opt => (_jsx("button", { onClick: () => onNeighborhoodDepthChange(opt.value), className: `px-2 py-0.5 rounded text-xs font-medium transition-all ${neighborhoodDepth === opt.value
                        ? 'bg-white/15 text-white'
                        : 'text-gray-400 hover:text-gray-200 hover:bg-white/5'}`, children: opt.label }, opt.value))) }), _jsxs("button", { onClick: onPathModeToggle, className: `flex items-center gap-1.5 glass-card rounded-lg px-3 py-1.5 border text-xs font-medium transition-all ${pathMode
                    ? 'border-indigo-400/40 bg-indigo-400/15 text-indigo-300 shadow-glow-sm-blue'
                    : 'text-gray-500 hover:text-gray-200 hover:bg-white/[0.05]'}`, children: [_jsx(Route, { size: 13 }), t('explorer:toolbar.pathDiscovery')] }), _jsxs("button", { onClick: onStructureHolesToggle, className: `flex items-center gap-1.5 glass-card rounded-lg px-3 py-1.5 border text-xs font-medium transition-all ${showStructureHoles
                    ? 'border-amber-500/40 bg-amber-500/15 text-amber-300 shadow-glow-sm-amber'
                    : 'text-gray-500 hover:text-gray-200 hover:bg-white/[0.05]'}`, children: [_jsx(Circle, { size: 13 }), t('explorer:toolbar.structureHoles')] }), maxConnectivity > 0 && (_jsxs("div", { className: "flex items-center gap-2 glass-card rounded-lg px-3 py-1.5 border border-white/10", children: [_jsx("span", { className: "text-xs text-gray-400 whitespace-nowrap", children: t('explorer:toolbar.connectivityLabel') }), _jsx("input", { type: "range", min: 0, max: maxConnectivity, value: connectivityThreshold, onChange: e => onConnectivityThresholdChange(Number(e.target.value)), className: "w-20 h-1 accent-indigo-400" }), _jsx("span", { className: "text-xs text-gray-400 tabular-nums w-4 text-right", children: connectivityThreshold })] })), graphLimit !== undefined && onGraphLimitChange && (_jsxs("div", { className: "flex items-center gap-2 glass-card rounded-lg px-3 py-1.5 border border-white/10", children: [_jsx("span", { className: "text-xs text-gray-400 whitespace-nowrap", children: t('explorer:toolbar.nodeLimitLabel', { defaultValue: 'Top' }) }), _jsxs("select", { value: graphLimit, onChange: e => onGraphLimitChange(Number(e.target.value)), className: "bg-transparent text-xs text-white tabular-nums focus:outline-none cursor-pointer", children: [_jsx("option", { value: 200, className: "bg-neutral-900", children: "200" }), _jsx("option", { value: 500, className: "bg-neutral-900", children: "500" }), _jsx("option", { value: 1000, className: "bg-neutral-900", children: "1000" }), _jsx("option", { value: 2000, className: "bg-neutral-900", children: "2000" })] }), renderedNodeCount !== undefined && (_jsxs("span", { className: "text-[10px] text-gray-500 tabular-nums whitespace-nowrap", title: t('explorer:toolbar.nodeLimitHint', { defaultValue: '按 heat 高低取前 N 个节点 + 它们的 1-hop 邻居' }), children: ["(", renderedNodeCount, ")"] }))] })), pathMode && (_jsx("div", { className: "bg-indigo-400/15 backdrop-blur rounded-lg px-3 py-1.5 border border-indigo-400/30", children: _jsx("span", { className: "text-xs text-indigo-300", children: pathFrom ? t('explorer:toolbar.clickSecondNode') : t('explorer:toolbar.clickStartNode') }) }))] }));
}
