import type { ReactNode } from 'react';
import type { GroupTab, ProcessingNode } from './types';
export declare const TRIGGER_PARAM_KEYS: Set<string>;
export declare const LLM_PARAM_KEYS: Set<string>;
export declare function classifyParam(key: string): 'trigger' | 'llm' | 'param';
export declare const GROUP_DESC_KEYS: Record<GroupTab, string>;
export declare const MEMORY_NODES: ProcessingNode[];
export declare const THINK_ASSOCIATE_NODES: ProcessingNode[];
export declare const THINK_EMERGE_NODES: ProcessingNode[];
export declare const OUTPUT_NODES: ProcessingNode[];
export declare const EVOLUTION_NODES: ProcessingNode[];
export declare const NODES_BY_GROUP: Record<GroupTab, ProcessingNode[]>;
export declare const TRIGGER_STYLES: Record<string, string>;
export declare const TRIGGER_ICONS: Record<string, ReactNode>;
export declare const TRIGGER_LABEL_KEYS: Record<string, string>;
